[build]
target = "x86_64-pc-windows-msvc"

[target.x86_64-pc-windows-msvc]
rustflags = [
    "-C", "target-feature=-mmx,-sse,-sse2,-sse3,-ssse3,-sse4.1,-sse4.2,-3dnow,-avx,-avx2,+soft-float",
    "-C", "link-arg=/SUBSYSTEM:NATIVE",
    "-C", "link-arg=/DRIVER",
    "-C", "link-arg=/ENTRY:DriverEntry",
    "-C", "link-arg=/NODEFAULTLIB"
]
